//// Generated by Selenium IDE
//using System;
//using System.Collections;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading;
//using OpenQA.Selenium;
//using OpenQA.Selenium.Chrome;
//using OpenQA.Selenium.Firefox;
//using OpenQA.Selenium.Remote;
//using OpenQA.Selenium.Support.UI;
//using OpenQA.Selenium.Interactions;
//using NUnit.Framework;
//[TestFixture]
//public class LoginandcheckoutTest {
//  private IWebDriver driver;
//  public IDictionary<string, object> vars {get; private set;}
//  private IJavaScriptExecutor js;
//  [SetUp]
//  public void SetUp() {
//    driver = new ChromeDriver();
//    js = (IJavaScriptExecutor)driver;
//    vars = new Dictionary<string, object>();
//  }
//  [TearDown]
//  protected void TearDown() {
//    driver.Quit();
//  }
//  [Test]
//  public void loginandcheckout() {
//    driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/demo-site/");
//    driver.Manage().Window.Size = new System.Drawing.Size(1009, 1085);
//    driver.FindElement(By.LinkText("My account")).Click();
//    driver.FindElement(By.Id("username")).SendKeys("afraaz.tiwana@nfocus.co.uk");
//    driver.FindElement(By.Id("password")).SendKeys("nfocusTesting123");
//    driver.FindElement(By.CssSelector("html")).Click();
//    driver.FindElement(By.Name("login")).Click();
//    driver.FindElement(By.LinkText("Shop")).Click();
//    driver.FindElement(By.CssSelector(".post-28 > .button")).Click();
//    driver.FindElement(By.LinkText("View cart")).Click();
//    driver.FindElement(By.Id("coupon_code")).Click();
//    driver.FindElement(By.Id("coupon_code")).SendKeys("edgewords");
//    driver.FindElement(By.Name("apply_coupon")).Click();
//    {
//      var element = driver.FindElement(By.Name("apply_coupon"));
//      Actions builder = new Actions(driver);
//      builder.MoveToElement(element).Perform();
//    }
//    {
//      var element = driver.FindElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.MoveToElement(element, 0, 0).Perform();
//    }
//    driver.FindElement(By.LinkText("Proceed to checkout")).Click();
//    driver.FindElement(By.LinkText("My account")).Click();
//    driver.FindElement(By.LinkText("Logout")).Click();
//    driver.FindElement(By.Id("username")).SendKeys("afraaz.tiwana@nfocus.co.uk");
//    driver.FindElement(By.Id("password")).SendKeys("nfocusTesting123");
//  }
//}
